spring.application.name=employee

server.servlet.context-path= /api/v1

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=company
spring.data.mongodb.username=company
spring.data.mongodb.password=password

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.apache.catalina=DEBUG